Output hookshot.gif
Set Width 1400
Set Height 1000
Set FontFamily "JetBrainsMono Nerd Font Mono"
Set Shell zsh
Sleep 500ms
Type "gh hookshot --owner marcelblijleven --repo hooktest"
Enter
Sleep 1.0s
Type "]"
Sleep 500ms
Type "]"
Sleep 1.0s
Type "["
Sleep 1.0s
Type "["
Sleep 1.0s
Down 1
Sleep 500ms
Down 1
Sleep 500ms
Down 1
Sleep 500ms
Type "]"
Sleep 500ms
Type "]"
Sleep 500ms
Up 1
Sleep 500ms
Up 1
Sleep 500ms
Up 1
Sleep 500ms
Right
Down 10
Sleep 2s

